### ISSUE TITLE
建议在github中维护一份带版本号的二进制版本

### ISSUE THREAD

**Issue by asins** [zfdang/chinese-lunar-calendar-for-mac#18]
过年期间重装了一次系统，使用的软件基本上用`brew cask`安装好了，但您开发的WanNianLi app只能在你的网站中下载。

所以就为brew cask提交了一份WanNianLi.app的安装脚本，但brew建议在github中维护软件版本，所以希望你在github Releases中放一份，这样使用者更新起来方便。
我提交的cask pull: https://github.com/Homebrew/homebrew-cask/pull/100124

**Comment by zfdang** [comment]
刚放了一个到release里去

不过release里的内容，在国内下载比较慢，所以我一般都放到www里了

**Comment by asins** [comment]
不放在github releases中可是可以的，但需要为下载的URL加入版本号信息，这样编写的脚本也可以。

**Comment by asins** [comment]
@zfdang 看官网已区分ARM系统、Intel系统的两个版本，请再在github Releases中提供下两个版本信息
