### ISSUE TITLE
请问是否可以增加支持M1芯片

### ISSUE THREAD

**Issue by xshwy** [zfdang/chinese-lunar-calendar-for-mac#19]
请问是否可以增加支持M1芯片 当前版本可以打开 但是在任务栏没有任何图标显示 在Monitor中也还是可以看到进程存在的

**Comment by zfdang** [comment]
试试这个看行不行：
http://calendar.zfdang.com/WanNianLi.app-u.zip

**Comment by xshwy** [comment]
> 试试这个看行不行： http://calendar.zfdang.com/WanNianLi.app-u.zip

可以啦 非常感谢 超级喜欢您的这款作品
