### ISSUE TITLE
农历的节日设置10月有问题

### ISSUE THREAD

**Issue by ruoqianfengshao** [zfdang/chinese-lunar-calendar-for-mac#3]
![image](https://cloud.githubusercontent.com/assets/2928664/7799300/e5f7109c-0336-11e5-99c2-d120e8787b46.png)
如上图设置，对应的农历 10月29 那天并不会显示妈妈生日；
我尝试改了一下js的G(h)，当`h >=10`，在浏览器下已经好了，但是打包出来的app还是有问题，希望能解决一下
修改如下

``` javascript
 function G(h) {
    return h < 10 ? "0" + h : h.toString()
 }
```

>  ps: 没接触过os x开发，折腾了一天没能解决

**Comment by zfdang** [comment]
做这样的改动不需要打包app,  直接安装原始的包，然后修改vim ~/Library/Application\ Support/com.zfdang.calendar/festivals.js 这个文件就行了

可能修改完之后，需要重新启动一下 $ sudo killall SystemUIServer

**Comment by ruoqianfengshao** [comment]
嗯改了之后10月份的农历还是不生效，其他的都生效了。
`G(this.lunarMonth) + G(this.lunarDate)`
当 this.lunarMonth 和 this.lunarDate 都大于10 的时候，想加的值是一个整型，不是string，所以在festivals.js 里面匹配不到

**Comment by zfdang** [comment]
改正了
