### ISSUE TITLE
Command + Drag 无法拖动

### ISSUE THREAD

**Issue by amorphobia** [zfdang/chinese-lunar-calendar-for-mac#6]
MacBook Pro 2012 年中 13寸，系统是 10.10.5

自带图标可以拖动，但 WanNianLi 的图标不可以。

**Comment by zfdang** [comment]
请看说明 @ calendar.zfdang.com

**Comment by amorphobia** [comment]
我是按照说明操作的，然而cmd+drag不能改变图标位置。

**Comment by amorphobia** [comment]
Sorry 没注意到有两个版本，那么请问 10.10.5 可以使用非官方 API 版本吗？

**Comment by zfdang** [comment]
10.10.5应该也可以用非官方API版本的

On Mon, Sep 7, 2015 at 10:18 PM, amorphobia <notifications@github.com>
wrote:

> Sorry 没注意到有两个版本，那么请问 10.10.5 可以使用非官方 API 版本吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfdang/chinese-lunar-calendar-for-mac/issues/6#issuecomment-138309819>
> .
>



-- 
   Regards!
-------------------------------------------
Zhengfa
-------------------------------------------
