### ISSUE TITLE
农历的每个月的第一天显示月份

### ISSUE THREAD

**Issue by lianqiw** [zfdang/chinese-lunar-calendar-for-mac#7]
如题。现在的显示方式无法知道是哪一月。

**Comment by zfdang** [comment]
现在就是这样的啊
![Uploading Snip20150916_3.png…]()

**Comment by lianqiw** [comment]
这是我的电脑显示的
<img width="424" alt="screen shot 2015-09-15 at 5 49 47 pm" src="https://cloud.githubusercontent.com/assets/158336/9893877/3de20b06-5bd2-11e5-844b-590cbe47d837.png">

**Comment by zfdang** [comment]
你的是哪一个版本的啊？农历日期貌似都不太对啊

On Wed, Sep 16, 2015 at 8:50 AM, Lianqi Wang <notifications@github.com>
wrote:

> 这是我的电脑显示的
> [image: screen shot 2015-09-15 at 5 49 47 pm]
> <https://cloud.githubusercontent.com/assets/158336/9893877/3de20b06-5bd2-11e5-844b-590cbe47d837.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfdang/chinese-lunar-calendar-for-mac/issues/7#issuecomment-140589442>
> .
>



-- 
   Regards!
-------------------------------------------
Zhengfa
-------------------------------------------

**Comment by lianqiw** [comment]
就在你网站上新下的。是不是因为我是在-7时区？

**Comment by lianqiw** [comment]
请问这个农历显示差一天能修复吗

**Comment by zfdang** [comment]
缺失是时区的问题导致的，在尝试着修复这个问题...

**Comment by zfdang** [comment]
已经修正了，请下载最新版的wannianli.app

**Comment by lianqiw** [comment]
非常感谢
