### ISSUE TITLE
OS X 10.11 (15A284) 不能用。

### ISSUE THREAD

**Issue by xuejinwei** [zfdang/chinese-lunar-calendar-for-mac#8]
刚刚升级了最新版的OS X 10.11 (15A284)，万年历不能用了，打不开

**Comment by lianqiw** [comment]
我这里打得开，但是拖动图标的功能不好使了

**Comment by zfdang** [comment]
10.11的API有变化，所以原来的使用黑科技的方法就不好使了，只能使用官方api了。大家注意看calendar.zfdang.com的说明，有两个版本的代码下载，10.11只能使用官方的版本。



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.3.5&pv=5.1.1&source=email_footer_2] On 星期五, 10月 02, 2015 at 1:17 AM, Lianqi Wang < notifications@github.com [notifications@github.com] > wrote:
我这里打得开，但是拖动图标的功能不好使了

—
Reply to this email directly or view it on GitHub
[https://github.com/zfdang/chinese-lunar-calendar-for-mac/issues/8#issuecomment-144790293] .[https://github.com/notifications/beacon/ABLwbE_4YxyhJFWwAUyT0AYt4yh-UbgKks5o3WHpgaJpZM4GHRpu.gif]
